<a href="https://colab.research.google.com/github/NatWhitt/AIDI-Assignment/blob/main/AIDI_Data_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# 1. Load your CSV file
df = pd.read_csv('Assignment data premessage.csv')
df.head()

,Student,Date,Time,Reason,Type
0,Jessica-Susan Anderson,09-12-2025,12:20:00,Lateness to School and/or lessons.,Lateness
1,Walter Page,12-02-2026,16:00:00,Repeatedly unbuckling his seat belt on a schoo...,School
2,Michael-Lawrence Robinson,05-02-2026,13:00:00,Failure to complete Science Sparx prep. Please...,Department
3,Sarah Green,15-10-2025,12:50:00,3x warnings accrued since the beginning of hal...,Head of Year
4,Emily Vargas-Majors,02-12-2025,12:20:00,Lateness to School and/or lessons.,Lateness

In [ ]:
from numpy import random
def format_message(row):
  if random.randint(0, 2) == 0:
    return f"{row['Type']} detention set for {row['Student']} on {row['Date']} at {row['Time']}. Reason: {row['Reason']}",
  elif random.randint(0, 2) == 1:
    return f"{row['Student']} has been set a detention for {row['Type']} on {row['Date']} at {row['Time']}. For the reason of {row['Reason']}",
  elif random.randint(0, 2) == 2:
    return f"Add {row['Student']} into a detention {row['Type']} on {row['Date']} at {row['Time']}. For the reason of {row['Reason']}",

In [ ]:
df['Message'] = df.apply(
      lambda row: f"{row['Type']} detention set for {row['Student']} on {row['Date']} at {row['Time']}. For {row['Reason']}",
      axis=1
)

In [ ]:
df.head()

,Student,Date,Time,Reason,Type,Message
0,Jessica-Susan Anderson,09-12-2025,12:20:00,Lateness to School and/or lessons.,Lateness,Lateness detention set for Jessica-Susan Ande...
1,Walter Page,12-02-2026,16:00:00,Repeatedly unbuckling his seat belt on a schoo...,School,School detention set for Walter Page on 12-02-...
2,Michael-Lawrence Robinson,05-02-2026,13:00:00,Failure to complete Science Sparx prep. Please...,Department,Department detention set for Michael-Lawrence ...
3,Sarah Green,15-10-2025,12:50:00,3x warnings accrued since the beginning of hal...,Head of Year,Head of Year detention set for Sarah Green on ...
4,Emily Vargas-Majors,02-12-2025,12:20:00,Lateness to School and/or lessons.,Lateness,Lateness detention set for Emily Vargas-Major...

In [ ]:
df.to_csv('Data with Message.csv', index=False)